# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Firstpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Login1 import Ui_Dialog_Login
from Cnu1 import Ui_Dialog_Create

class Ui_Dialog(object):

    def setupUi(self, Dialog):
        def login_page():
            self.Dialog = QtWidgets.QDialog()
            self.ul = Ui_Dialog_Login()
            self.ul.setupUi(self.Dialog)
            self.Dialog.show()
        def cnu_page():
            self.Dialog = QtWidgets.QDialog()
            self.uc = Ui_Dialog_Create()
            self.uc.setupUi(self.Dialog)
            self.Dialog.show()

        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 800)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1200, 800))
        self.widget.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(120, 40, 1011, 131))
        self.label.setStyleSheet("font: 36pt \"Modern No. 20\";\n"
"font: 75 italic 36pt \"Arial Narrow\";\n"
"background-color: rgb(255, 170, 127);")
        self.label.setObjectName("label")
        self.pushButton_Login = QtWidgets.QPushButton(self.widget)
        self.pushButton_Login.setGeometry(QtCore.QRect(390, 400, 201, 71))
        self.pushButton_Login.setAutoFillBackground(False)
        self.pushButton_Login.setStyleSheet("border-radius:10px;\n"
"font: 75 18pt \"Myanmar Text\";\n"
"color: rgb(255, 255, 255);\n"
"background-color:rgb(255, 103, 2);")

        self.pushButton_Login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))

        self.pushButton_Login.setObjectName("pushButton_Login")
        self.pushButton_Login.clicked.connect(login_page)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(380, 530, 321, 31))
        self.label_5.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";color:red;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(390, 310, 561, 41))
        self.label_2.setStyleSheet("font: 16pt \"Dubai\";\n"
"text-decoration: underline;")
        self.label_2.setObjectName("label_2")
        self.pushButton2_Cnu = QtWidgets.QPushButton(self.widget)
        self.pushButton2_Cnu.setGeometry(QtCore.QRect(620, 400, 241, 71))
        self.pushButton2_Cnu.setAutoFillBackground(False)
        self.pushButton2_Cnu.setStyleSheet("border-radius:10px;\n"
"font: 75 18pt \"Myanmar Text\";\n"
"color: rgb(255, 255, 255);\n"
"background-color:rgb(255, 103, 2);")
        self.pushButton2_Cnu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))

        self.pushButton2_Cnu.setObjectName("pushButton2_Cnu")
        self.pushButton2_Cnu.clicked.connect(cnu_page)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Welcome to Rashid Khodadad (Petrol Dept)"))
        self.pushButton_Login.setText(_translate("Dialog", "Login"))
        self.label_2.setText(_translate("Dialog", "Do you wish to login or create a new user?"))
        self.pushButton2_Cnu.setText(_translate("Dialog", "Create new user"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
