# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1003, 901)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1003, 26))
        self.menubar.setObjectName("menubar")
        self.menuMaster = QtWidgets.QMenu(self.menubar)
        self.menuMaster.setObjectName("menuMaster")
        self.menuCredit_Sale = QtWidgets.QMenu(self.menubar)
        self.menuCredit_Sale.setObjectName("menuCredit_Sale")
        self.menuReport = QtWidgets.QMenu(self.menubar)
        self.menuReport.setObjectName("menuReport")
        self.menuBackup = QtWidgets.QMenu(self.menubar)
        self.menuBackup.setObjectName("menuBackup")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCustomer_Master = QtWidgets.QAction(MainWindow)
        self.actionCustomer_Master.setObjectName("actionCustomer_Master")
        self.actionBranch_Master = QtWidgets.QAction(MainWindow)
        self.actionBranch_Master.setObjectName("actionBranch_Master")
        self.actionItem_Master = QtWidgets.QAction(MainWindow)
        self.actionItem_Master.setObjectName("actionItem_Master")
        self.actionBill_Report = QtWidgets.QAction(MainWindow)
        self.actionBill_Report.setObjectName("actionBill_Report")
        self.actionDaily_Credit_Sale_Report = QtWidgets.QAction(MainWindow)
        self.actionDaily_Credit_Sale_Report.setObjectName("actionDaily_Credit_Sale_Report")
        self.actionCustomer_Deposit_Report = QtWidgets.QAction(MainWindow)
        self.actionCustomer_Deposit_Report.setObjectName("actionCustomer_Deposit_Report")
        self.actionCustomerwise_Car_Bill_Report = QtWidgets.QAction(MainWindow)
        self.actionCustomerwise_Car_Bill_Report.setObjectName("actionCustomerwise_Car_Bill_Report")
        self.actionCustomerwise_Car_Summary = QtWidgets.QAction(MainWindow)
        self.actionCustomerwise_Car_Summary.setObjectName("actionCustomerwise_Car_Summary")
        self.actionCustomerwise_Summary_Report = QtWidgets.QAction(MainWindow)
        self.actionCustomerwise_Summary_Report.setObjectName("actionCustomerwise_Summary_Report")
        self.actionItem_wise_Summary_Report = QtWidgets.QAction(MainWindow)
        self.actionItem_wise_Summary_Report.setObjectName("actionItem_wise_Summary_Report")
        self.menuMaster.addAction(self.actionCustomer_Master)
        self.menuMaster.addSeparator()
        self.menuMaster.addAction(self.actionBranch_Master)
        self.menuMaster.addSeparator()
        self.menuMaster.addAction(self.actionItem_Master)
        self.menuReport.addAction(self.actionBill_Report)
        self.menuReport.addAction(self.actionDaily_Credit_Sale_Report)
        self.menuReport.addAction(self.actionCustomer_Deposit_Report)
        self.menuReport.addAction(self.actionCustomerwise_Car_Bill_Report)
        self.menuReport.addAction(self.actionCustomerwise_Car_Summary)
        self.menuReport.addAction(self.actionCustomerwise_Summary_Report)
        self.menuReport.addAction(self.actionItem_wise_Summary_Report)
        self.menubar.addAction(self.menuMaster.menuAction())
        self.menubar.addAction(self.menuCredit_Sale.menuAction())
        self.menubar.addAction(self.menuReport.menuAction())
        self.menubar.addAction(self.menuBackup.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuMaster.setTitle(_translate("MainWindow", "Master"))
        self.menuCredit_Sale.setTitle(_translate("MainWindow", "Credit Sale"))
        self.menuReport.setTitle(_translate("MainWindow", "Report"))
        self.menuBackup.setTitle(_translate("MainWindow", "Backup"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionCustomer_Master.setText(_translate("MainWindow", "Customer Master"))
        self.actionBranch_Master.setText(_translate("MainWindow", "Branch Master"))
        self.actionItem_Master.setText(_translate("MainWindow", "Item Master"))
        self.actionBill_Report.setText(_translate("MainWindow", "Bill Report"))
        self.actionDaily_Credit_Sale_Report.setText(_translate("MainWindow", "Daily Credit Sale Report"))
        self.actionCustomer_Deposit_Report.setText(_translate("MainWindow", "Customer Deposit Report"))
        self.actionCustomerwise_Car_Bill_Report.setText(_translate("MainWindow", "Customerwise Car Bill Report"))
        self.actionCustomerwise_Car_Summary.setText(_translate("MainWindow", "Customerwise Car Summary Report"))
        self.actionCustomerwise_Summary_Report.setText(_translate("MainWindow", "Customerwise Summary Bill Report"))
        self.actionItem_wise_Summary_Report.setText(_translate("MainWindow", "Item-wise Summary Report"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
